### ISSUE TITLE
How to initialize first generation child nodes?

### ISSUE THREAD

**Issue by Jeff123z** [MARIO-Math-Reasoning/Super_MARIO#6]
I'm curious about the way you explored the possible child nodes in training phase. For the 1st round playout, for a given question, randomly list several child nodes as possible first step for resolving the question? In AlphaZero, it's straightforward to randomly pick grid cells. Thanks

**Comment by lovecambi** [comment]
> I'm curious about the way you explored the possible child nodes in training phase. For the 1st round playout, for a given question, randomly list several child nodes as possible first step for resolving the question? In AlphaZero, it's straightforward to randomly pick grid cells. Thanks

You can refer to the [instruction](https://github.com/MARIO-Math-Reasoning/Super_MARIO?tab=readme-ov-file#mcts) in readme, about how to construct the training data of the round 1. 

Your thought is almost correct. As the instruction following ability of the initial LLM is weak, we use a standard REACT prompt with two-shot demonstrations (randomly sampled from 20 prepared examples). You can take a look at config file `https://github.com/MARIO-Math-Reasoning/Super_MARIO/blob/main/configs/mcts_round1.yaml` and the folder `https://github.com/MARIO-Math-Reasoning/Super_MARIO/tree/main/mcts_math/few_shots`. Then, starting from the root for the MCTS, each parent is allowed to generate `n_generate_sample` children nodes (if I understand correctly, this is your question and your guess is correct). In our case, we set `n_generate_sample=5`. If you have enough computational resources, you can set even larger. 

From the second round, we use our customized prompt in xml format without demonstration. Because the instruction following is stronger, we set larger temperature e.g. 1.0 to encourage more diverse children nodes.
